### ISSUE TITLE
Update Castle Windsor

### ISSUE THREAD

**Issue by danielearrighi** [RadicalFx/Radical.Windows.Presentation.CastleWindsor#37]
Hello,
I see there is, from a long time, a Castle Windows update (now 4.1) but cannot update because Radical Requires Windsor < 4.0.0. Will this be updated or it's incompatible?
Thanks

**Comment by mauroservienti** [comment]
I’ve just released 2.0.0-Beta.1 on nuget

**Comment by mauroservienti** [comment]
2.0.0 Released on Nuget. Thanks for you patience.
